# Generated by Django 5.1.4 on 2025-06-21 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id_source', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=250, null=True)),
                ('source_path', models.TextField(null=True)),
                ('source_type', models.CharField(max_length=250, null=True)),
                ('source_version', models.CharField(max_length=250, null=True)),
                ('source_os', models.CharField(max_length=250, null=True)),
                ('source_plugins', models.JSONField(null=True)),
                ('source_key', models.JSONField(default={'key_type': None, 'value': None})),
                ('source_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
            ],
        ),
    ]
