# Generated by Django 5.1.4 on 2025-06-21 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id_case', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_name', models.CharField(help_text='Le nom du cas', max_length=250, null=True)),
                ('case_description', models.CharField(help_text='La description du cas', max_length=250, null=True)),
                ('case_create', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
    ]
