# Generated by Django 5.1.4 on 2025-06-21 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id_artefact', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artefact_type', models.CharField(max_length=250, null=True)),
                ('artefact_values', models.JSONField(null=True)),
                ('artefact_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
                ('artefact_src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_path', models.TextField()),
                ('reg_parent', models.TextField()),
                ('reg_key', models.TextField()),
                ('reg_value', models.TextField()),
                ('reg_ts', models.DateTimeField()),
                ('reg_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeline_ts', models.DateTimeField()),
                ('timeline_value', models.CharField(max_length=500)),
                ('timeline_type', models.CharField(max_length=500)),
                ('timeline_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
                ('timeline_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
        ),
    ]
